assets:
    s3:
        region: 'eu-central-1'
        userBucket: 'maria.roman'
        bucketName: 'communities-guide-dev'
        acl: 'public-read'
        publicUrl: 'https://communities-guide-dev.s3.eu-central-1.amazonaws.com/images/'
        uploadLimit: 1000000

mongodb:
    schema:
        autoindex: true

serverURL: 'http://dev.com'

application:
    port: 8082
    debug: true
    uploadLimit: '2mb'
    timezone: 'Europe/Bucharest'

auth:
    jwt:
        secret:
        exp: 0
    bcrypt:
        iterations: 10
log:
    morgan:
        format: ':remote-addr - - [:date] ":method :url" :status :res[content-length] - ":user-agent" - :response-time ms'

facebookAuth:
    callbackURL: 'http://communities-guide-dev.elasticbeanstalk.com/auth/facebook/callback'

twitterAuth:
    callbackURL: 'http://communities-guide-dev.elasticbeanstalk.com/auth/twitter/callback'

session:
    secret: 'super secret session token'